[package]
name = "sqlx-pb"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.18.2", features = [
    "macros",
] }
sqlx = { version = "0.5.13", features = [
    "runtime-tokio-native-tls",
    "macros",
    "postgres",
    "json",
] }

serde = "1.0.137"
serde_json = "1.0.81"