version: '3.7'

services:

  db:
    image: postgres:12.9-alpine
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - '127.0.0.1:5433:5432'
    environment:
      POSTGRES_PASSWORD: leak-ok-123
      POSTGRES_DB: my_app